In [2]:
import tensorflow as tf

In [3]:
a = tf.fill([2,2],2.0)
b = tf.ones([2,2])

In [4]:
print(a+b)
print(a-b)
print(a/b)
print(a*b)

tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)


In [5]:
print(b//a)
print(b%a)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [8]:
print(tf.math.log(a))
print(tf.math.log(8.)/tf.math.log(2.))

tf.Tensor(
[[0.6931472 0.6931472]
 [0.6931472 0.6931472]], shape=(2, 2), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)


In [7]:
tf.exp(a)

<tf.Tensor: id=13, shape=(2, 2), dtype=float32, numpy=
array([[7.389056, 7.389056],
       [7.389056, 7.389056]], dtype=float32)>

In [9]:
print(tf.pow(b,3))
print(b**3)
print(tf.sqrt(b))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [10]:
tf.matmul(a,b) # matrix 相乘

<tf.Tensor: id=25, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [11]:
# Y=X@W+b
x = tf.ones([4,2])
w = tf.ones([2,1])
b = tf.constant(0.3)
x@w+b

<tf.Tensor: id=34, shape=(4, 1), dtype=float32, numpy=
array([[2.3],
       [2.3],
       [2.3],
       [2.3]], dtype=float32)>