# Vector Norm
- Eukl Norm $||x||_2 = [\sum_kx^2_k]^{\frac{1}{2}}$
- Max norm
- $L_1$ Norm

In [1]:
import tensorflow as tf

### L1 Norm

In [2]:
a = tf.ones([2,2])

$\sqrt{1^2+1^2+1^2+1^2}$

In [3]:
tf.norm(a) 

<tf.Tensor: id=7, shape=(), dtype=float32, numpy=2.0>

In [4]:
tf.sqrt(tf.reduce_sum(tf.square(a))) # equal tf.norm

<tf.Tensor: id=11, shape=(), dtype=float32, numpy=2.0>

In [5]:
b = tf.ones([2,2])

In [6]:
tf.norm(b)

<tf.Tensor: id=19, shape=(), dtype=float32, numpy=2.0>

\begin{array}{cc}
1 & 1\\
1 & 1\\
\end{array}

\begin{array}{cc}
\sqrt{2}\\
\sqrt{2}\\
\end{array}

In [7]:
tf.norm(b, ord=2, axis=1) # 對每一列進行範數，ord 2 為 L2 範數

<tf.Tensor: id=24, shape=(2,), dtype=float32, numpy=array([1.4142135, 1.4142135], dtype=float32)>

In [12]:
tf.norm(b, ord=1) # L1 範數 |1|+|1|+|1|+|1|

<tf.Tensor: id=40, shape=(), dtype=float32, numpy=4.0>

In [9]:
tf.norm(b, ord=1, axis=0) # 對每一行進行範數

<tf.Tensor: id=32, shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [10]:
tf.norm(b, ord=1, axis=1)# 對每一列進行範數

<tf.Tensor: id=36, shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

## reduce

In [14]:
c = tf.random.normal([4,10])
print(c)

tf.Tensor(
[[ 1.3338864   0.54926026  0.1362242  -0.69363624  0.8512554   0.74987894
   1.5939469  -1.2576302  -0.7232043   0.18487196]
 [-1.6176319   0.10982297 -0.62117964  0.19919418  0.83808744 -0.72189754
  -1.7031595   0.37753403 -0.30125028 -0.3746686 ]
 [-0.01734839  1.0708019  -0.16281351 -0.66021705 -0.7157932  -0.27657712
  -0.8662319   1.2860074  -1.0724266  -0.6460208 ]
 [ 0.7480791  -1.9353622  -1.2769027   0.8750248   1.5702485  -0.8447398
   1.5438606   0.43784568 -0.7043965  -0.1395337 ]], shape=(4, 10), dtype=float32)


In [16]:
tf.reduce_min(c), tf.reduce_max(c), tf.reduce_mean(c)

(<tf.Tensor: id=60, shape=(), dtype=float32, numpy=-1.9353622>,
 <tf.Tensor: id=62, shape=(), dtype=float32, numpy=1.5939469>,
 <tf.Tensor: id=64, shape=(), dtype=float32, numpy=-0.07191976>)

In [17]:
tf.reduce_min(c, axis=1), tf.reduce_max(c, axis=1), tf.reduce_mean(c, axis=1)

(<tf.Tensor: id=66, shape=(4,), dtype=float32, numpy=array([-1.2576302, -1.7031595, -1.0724266, -1.9353622], dtype=float32)>,
 <tf.Tensor: id=68, shape=(4,), dtype=float32, numpy=array([1.5939469 , 0.83808744, 1.2860074 , 1.5702485 ], dtype=float32)>,
 <tf.Tensor: id=70, shape=(4,), dtype=float32, numpy=array([ 0.27248532, -0.38151485, -0.20606193,  0.02741238], dtype=float32)>)

## argmax and argmin

In [19]:
a = tf.random.normal([4,10])
print(a)

tf.Tensor(
[[-3.0841436e+00 -7.3822778e-01 -2.8823109e-03 -1.3967370e+00
   2.0590100e-01 -9.4958401e-01  1.1273787e-01 -1.7920280e+00
  -1.8820737e-01  3.8256121e-01]
 [-4.0551227e-01  1.0880674e-01 -6.3423812e-01  1.1002179e-01
  -4.8701724e-01 -1.0553240e+00  1.0306121e+00 -1.6246108e+00
  -1.6647001e-01  3.2022274e-01]
 [-2.9648826e+00 -7.0243704e-01 -7.9241085e-01 -1.2799956e+00
   1.2853202e+00 -4.4263473e-01  8.3887345e-01 -3.4852153e-01
   1.1127861e+00 -3.7485543e-01]
 [-5.8613473e-01 -1.3860939e-01 -9.8952550e-01  5.5892754e-01
  -1.1008066e+00  9.4770294e-01 -1.2103714e+00 -6.0916561e-01
  -2.9051363e-01  4.7583756e-01]], shape=(4, 10), dtype=float32)


In [21]:
tf.argmax(a)

<tf.Tensor: id=86, shape=(10,), dtype=int64, numpy=array([1, 1, 0, 3, 2, 3, 1, 2, 2, 3], dtype=int64)>

In [22]:
tf.argmin(a)

<tf.Tensor: id=88, shape=(10,), dtype=int64, numpy=array([0, 0, 3, 0, 3, 1, 3, 0, 3, 2], dtype=int64)>

## equal

In [23]:
v = tf.constant([1,2,3,4,5,6])
b = tf.range(6)

In [24]:
tf.equal(v ,b)

<tf.Tensor: id=94, shape=(6,), dtype=bool, numpy=array([False, False, False, False, False, False])>

In [25]:
a = tf.constant([[0.1, 0.2, 0.7],[0.9, 0.05, 0.05]])
a.shape

TensorShape([2, 3])

In [27]:
pred = tf.cast(tf.argmax(a ,axis=1), dtype=tf.int32)
print(pred)

tf.Tensor([2 0], shape=(2,), dtype=int32)


## unique

In [28]:
a = tf.constant([[0.1, 0.2, 0.7, 0.2],[0.9, 0.05, 0.05, 0.6]])

In [30]:
tf.unique(a[0]) # tf.gather(unique, idx) 可還原

Unique(y=<tf.Tensor: id=107, shape=(3,), dtype=float32, numpy=array([0.1, 0.2, 0.7], dtype=float32)>, idx=<tf.Tensor: id=108, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 1])>)

## Sort

In [31]:
a = tf.random.shuffle(tf.range(5))

In [33]:
tf.sort(a, direction='DESCENDING')

<tf.Tensor: id=121, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [37]:
tf.argsort(a, direction='DESCENDING') # 返回 index

<tf.Tensor: id=151, shape=(5,), dtype=int32, numpy=array([3, 0, 4, 1, 2])>

In [35]:
idx = tf.argsort(a, direction='DESCENDING')

In [36]:
tf.gather(a, idx)

<tf.Tensor: id=142, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [38]:
n = tf.constant([[4,6,9],[2,5,1], [8,3,6]])

In [42]:
res = tf.math.top_k(n, 2) # 返回 2個
res.indices # 回傳 index

<tf.Tensor: id=161, shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 0],
       [0, 2]])>

In [43]:
res.values

<tf.Tensor: id=160, shape=(3, 2), dtype=int32, numpy=
array([[9, 6],
       [5, 2],
       [8, 6]])>

Top-k accuracy，取前 k 個與 Label 進行比較

In [44]:
prob = tf.constant([[0.1, 0.2, 0.7], [0.2, 0.7, 0.1]])
label = tf.constant([2, 0])

In [46]:
k_b = tf.math.top_k(prob, 3).indices
print(k_b)

tf.Tensor(
[[2 1 0]
 [1 0 2]], shape=(2, 3), dtype=int32)


In [47]:
k_b = tf.transpose(k_b, [1,0])
print(k_b)

tf.Tensor(
[[2 1]
 [1 0]
 [0 2]], shape=(3, 2), dtype=int32)


In [49]:
target = tf.broadcast_to(label, [3,2])
print(target)

tf.Tensor(
[[2 0]
 [2 0]
 [2 0]], shape=(3, 2), dtype=int32)
