In [1]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.reshape(tf.range(9), [3,3])

In [4]:
# [[0,0],[0,0]] 配合維度
# [[列上,列下],[欄左, 欄右]]
tf.pad(a, [[0,0],[0,0]])

<tf.Tensor: id=12, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [5]:
tf.pad(a, [[1,0],[0,0]])

<tf.Tensor: id=14, shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [6]:
tf.pad(a, [[1,1],[0,0]])

<tf.Tensor: id=16, shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])>

In [7]:
tf.pad(a, [[1,1],[1,0]])

<tf.Tensor: id=18, shape=(5, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 1, 2],
       [0, 3, 4, 5],
       [0, 6, 7, 8],
       [0, 0, 0, 0]])>

In [8]:
tf.pad(a, [[1,1],[1,1]])

<tf.Tensor: id=20, shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 3, 4, 5, 0],
       [0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0]])>

![](https://missinglink.ai/wp-content/uploads/2019/03/Frame-2.png)

In [10]:
tf.pad(a, [[2,2],[2,0]])

<tf.Tensor: id=28, shape=(7, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2],
       [0, 0, 3, 4, 5],
       [0, 0, 6, 7, 8],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

## tile

In [11]:
tf.tile(a,[1, 2]) # [1, 2] 1 保持不變（列），2 表示複製一次（欄）

<tf.Tensor: id=30, shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

In [12]:
tf.tile(a,[2, 1])

<tf.Tensor: id=32, shape=(6, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [13]:
tf.tile(a,[3, 3]) # 由較小維度進行複製

<tf.Tensor: id=34, shape=(9, 9), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])>