In [13]:
import tensorflow as tf
import numpy as np

In [2]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [4]:
tf.constant(1., dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

# get GPU CPU

In [6]:
tf.device("cpu")
tf.device("gpu")

In [7]:
with tf.device("cpu"):
    a = tf.constant([1,2])
with tf.device("gpu"):
    b = tf.range(4)

##### 轉 numpy

In [8]:
b.numpy()

array([0, 1, 2, 3])

In [10]:
b.ndim

1

In [11]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [12]:
c = tf.rank(tf.ones([3,4,2]))
print(c)

tf.Tensor(3, shape=(), dtype=int32)


## Check Tensor type

In [15]:
a = tf.constant([1.])
b = tf.constant([True, False])
c = tf.constant('hello, world')
d = np.arange(4)

In [17]:
isinstance(a, tf.Tensor)

True

In [18]:
tf.is_tensor(d)

False

## Convert

In [19]:
a = np.arange(5)

In [22]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [24]:
aa = tf.convert_to_tensor(a, dtype=tf.int32)
print(aa)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [25]:
tf.cast(aa, dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [26]:
b = tf.constant([0,1])
tf.cast(b, dtype=tf.bool)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

## Variable

In [27]:
a = tf.range(5)

In [28]:
b = tf.Variable(a)
print(b.dtype)
print(b.name)

<dtype: 'int32'>
Variable:0


In [29]:
b = tf.Variable(a, name="input_data")
print(b.name)

input_data:0


In [30]:
b.trainable # 表示該變量能進行變化，微分、倒數 等

True

In [31]:
b.numpy()

array([0, 1, 2, 3, 4])

In [32]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [34]:
tf.convert_to_tensor([[2,3],[4,5]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [36]:
"""
tf.zeros 相對應的有 tf.ones
"""
tf.zeros([1, 2]) # [shape, shape]
tf.zeros([1, 2, 5]) # [shape, shape]

<tf.Tensor: shape=(1, 2, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [37]:
a = tf.zeros([2,3,3])
tf.zeros_like(a) # 傳回相對應維度值為 0 的 tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [38]:
tf.fill([2,3], 2) # 填充自己想要的值

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [2, 2, 2]])>

In [39]:
"""
Normal
"""
tf.random.normal([2,2], mean=1, stddev=3) # 預設是正態

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-3.4203463 , -0.02044463],
       [ 2.6272528 ,  0.23466086]], dtype=float32)>

In [40]:
tf.random.truncated_normal([2,2], mean=2, stddev=5) # 部分截斷並重新採樣

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-7.039528 ,  4.236894 ],
       [-1.3657095,  0.910915 ]], dtype=float32)>

In [42]:
tf.random.uniform([2,2], minval=1, maxval=3) # 均勻採樣

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.1103888, 1.8329792],
       [1.606333 , 1.4201467]], dtype=float32)>

##### Random Permutation

In [44]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)
print(idx)

tf.Tensor([7 6 2 8 1 9 0 3 4 5], shape=(10,), dtype=int32)


In [45]:
a = tf.random.normal([10,784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)
print(b)

tf.Tensor([5 9 3 4 0 1 9 0 8 0], shape=(10,), dtype=int32)


In [46]:
a = tf.gather(a, idx)
b = tf.gather(b, idx)
print(a)
print(b)

tf.Tensor(
[[ 0.0680942  -2.7274673  -0.51175004 ...  1.560178    0.2437137
  -0.17606385]
 [-0.51174927 -0.28651658  1.1296108  ...  1.5829458  -0.44448063
   1.4240694 ]
 [-0.23964043 -0.26936048  0.33684412 ... -0.8733141  -1.2034228
  -0.16405503]
 ...
 [-0.5858711   1.5394683   0.43479747 ... -0.6470356  -0.1435075
  -0.03579396]
 [ 1.3097812  -0.74104905 -0.32886887 ...  0.24848562  1.1698933
  -0.18387742]
 [-1.3134357  -0.4428609  -0.5041529  ...  1.158085    0.8624417
  -0.38771945]], shape=(10, 784), dtype=float32)
tf.Tensor([0 9 3 8 9 0 5 4 0 1], shape=(10,), dtype=int32)


## Loss

In [47]:
out = tf.random.uniform([4, 10])

In [48]:
y = tf.range(4)
y = tf.one_hot(y, depth=10)
print(y)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [49]:
loss = tf.keras.losses.mse(y ,out)
print(loss)

tf.Tensor([0.2856621  0.3608199  0.4285707  0.29890546], shape=(4,), dtype=float32)


In [50]:
loss = tf.reduce_mean(loss)
print(loss)

tf.Tensor(0.34348953, shape=(), dtype=float32)


## Vector

In [51]:
net = tf.keras.layers.Dense(10)
net.build((4,8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.36103183,  0.33224332,  0.45613146, -0.32338548,  0.05066079,
         0.52952826, -0.24672556,  0.07853127,  0.06601346, -0.11591801],
       [-0.5770642 , -0.48241842, -0.4584224 , -0.560372  , -0.3208775 ,
         0.33952326, -0.30893558,  0.42517793,  0.48207235,  0.17340368],
       [-0.36484143,  0.4972756 ,  0.5560132 , -0.2084839 , -0.44576085,
        -0.3462708 ,  0.37291962,  0.5282999 , -0.39673603,  0.13171566],
       [ 0.16696215,  0.40876687, -0.12289444, -0.5027142 , -0.27528003,
         0.24876899,  0.29157174, -0.02223271, -0.44424254,  0.20463586],
       [-0.07168424,  0.23248267,  0.34666473, -0.09116614, -0.49220553,
        -0.4165675 , -0.49376607, -0.29343525,  0.41061467, -0.30805764],
       [-0.25732127, -0.20065913, -0.08049473, -0.08700386,  0.13839185,
        -0.4436677 ,  0.5641731 ,  0.3434649 , -0.46727198, -0.04196018],
       [ 0.16376138, -0.53902185,  0.42881823,  0.20498866

In [52]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

## Matrix

In [54]:
x = tf.random.normal([4, 784])
net = tf.keras.layers.Dense(10)
net.build((4, 784))
net(x).shape
print(net.kernel.shape)
print(net.bias.shape)

(784, 10)
(10,)


## indexing

In [57]:
a = tf.ones([1,5,5,3])

In [58]:
a[0][0]

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [59]:
a[0][0][3]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [60]:
a = tf.range(10)
print(a)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [61]:
# a[start:end]
print(a[-1:])
print(a[-2:])
print(a[:2])
print(a[:-1])

tf.Tensor([9], shape=(1,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [64]:
# a[start:end:step]
c = tf.random.normal([4,28,28,3])
print(c.shape)

(4, 28, 28, 3)


In [67]:
print(c[0:2,:,:,:].shape)
print(c[:,0:28:4,0:28:4,:].shape)

(2, 28, 28, 3)
(4, 7, 7, 3)


In [68]:
a = tf.range(4)
print(a)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [69]:
# ::-1 倒序
a[::-1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 1, 0])>

In [70]:
print(a[::-2])
print(a[2::-2]) # -2 是 step

tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor([2 0], shape=(2,), dtype=int32)


In [71]:
# ...
a = tf.random.normal([2,4,28,28,3])
a.shape

TensorShape([2, 4, 28, 28, 3])

In [73]:
a[0,...].shape # 等於 a[0,:,:,:,:]

TensorShape([4, 28, 28, 3])

In [74]:
a[0,...,2].shape # 等於 a[0,:,:,:,2]

TensorShape([4, 28, 28])

## selecctive Indexing

In [77]:
# [class, students, subject]
x = tf.random.normal([4,35,8])
x.shape

TensorShape([4, 35, 8])

In [79]:
tf.gather(x, axis=0, indices=[2,3]).shape # a[2:4]

TensorShape([2, 35, 8])

In [80]:
tf.gather(x, axis=1, indices=[2,3,7,9,16]).shape

TensorShape([4, 5, 8])

In [81]:
# axis 取的維度 
#indices 取 subject 的其中三個
tf.gather(x, axis=2, indices=[2,3,7]).shape 

TensorShape([4, 35, 3])

In [82]:
tf.gather_nd(x, [0]).shape # 取第 0 個班級

TensorShape([35, 8])

In [83]:
tf.gather_nd(x, [0,1]).shape # 取第 0 個班級的第一個學生

TensorShape([8])

In [84]:
tf.gather_nd(x, [[0,1,2]]).shape # 返回一個陣列

TensorShape([1])

In [85]:
tf.gather_nd(x, [[0,0],[1,1]]).shape # 取第 0 班級的第 0 學生所有成績和取第 1 班級的第 1 學生所有成績

TensorShape([2, 8])

In [86]:
tf.gather_nd(x, [[0,0,0],[1,1,1],[2,2,2]]).shape #取第 0 班級的第 0 學生第 0 科成績和取第 1 班級的第 1 學生第 1 科成績與取第 2 班級的第 2 學生第 2 科成績

TensorShape([3])

In [87]:
tf.gather_nd(x, [[[0,0,0],[1,1,1],[2,2,2]]]).shape # 將上半部的值封裝程一個陣列

TensorShape([1, 3])

In [88]:
xx = tf.random.normal([4,28,28,3])
xx.shape

TensorShape([4, 28, 28, 3])

In [90]:
tf.boolean_mask(xx, mask=[True, True, False, False]).shape

TensorShape([2, 28, 28, 3])

In [91]:
tf.boolean_mask(xx, mask=[True, True, False], axis=3).shape

TensorShape([4, 28, 28, 2])

In [93]:
c = tf.ones([2,3,4])
tf.boolean_mask(c, mask=[[True, True, False], [False, True, True]]).shape
print(tf.boolean_mask(c, mask=[[True, True, False], [False, True, True]]))

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


# 維度轉換

In [95]:
a = tf.random.normal([4,28,28,3]) # 以圖為例

In [97]:
tf.reshape(a, [4, 784 ,3]).shape #[batch, pixel, channel]

TensorShape([4, 784, 3])

In [98]:
tf.reshape(a, [4, -1 ,3]).shape

TensorShape([4, 784, 3])

In [99]:
tf.reshape(a, [4, -1]).shape

TensorShape([4, 2352])

In [100]:
tf.reshape(tf.reshape(a, [4, -1]), [4, 28, 28, 3]).shape

TensorShape([4, 28, 28, 3])

In [101]:
tf.reshape(tf.reshape(a, [4, -1]), [4, 14, 56, 3]).shape

TensorShape([4, 14, 56, 3])

##### transpose
恢復時，不對原有矩陣影響

In [102]:
a = tf.random.normal([4,3,2,1])

In [103]:
tf.transpose(a).shape # 軸的交換

TensorShape([1, 2, 3, 4])

In [104]:
tf.transpose(a, perm=[0,2,1,3]).shape # perm=[0,2,1,3]) 定義原維度最後交換結果

TensorShape([4, 2, 3, 1])

##### Squeeze and Expand_dims

In [106]:
s = tf.random.normal([4,35,8])

In [107]:
tf.expand_dims(s, axis=0).shape

TensorShape([1, 4, 35, 8])

In [108]:
tf.expand_dims(s, axis=3).shape # axis 在第三軸的前一軸增加

TensorShape([4, 35, 8, 1])

In [109]:
tf.expand_dims(s, axis=-4).shape # axis 給負值回在後面一軸增加

TensorShape([1, 4, 35, 8])

In [110]:
tf.squeeze(tf.zeros([1,2,1,1,3])).shape # squeeze 將維度一的軸拿掉

TensorShape([2, 3])

In [116]:
t = tf.zeros([1,2,1,3])

In [117]:
tf.squeeze(t , axis=2).shape

TensorShape([1, 2, 3])

In [118]:
tf.squeeze(t , axis=-2).shape

TensorShape([1, 2, 3])

## Broadcasting