In [1]:
import numpy as np

# Softmax

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/001ce4c2c74e78a66a4d7d04ab92cbd0d0fdec02)

In [9]:
import math
import numpy as np
def softmax(z):
    z_x = [math.exp(i) for i in z]
    sum_z_x = sum(z_x)
    return [i / sum_z_x for i in z_x]
def np_softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0) 

In [15]:
import tensorflow as tf
n = [1.0, 2.0, 2.0, 5.0]
print(softmax(n))
print(np_softmax(n))
print(tf.nn.softmax(n))
print(np.sum(softmax(n)))

[0.01638411879964008, 0.04453665240837586, 0.04453665240837586, 0.8945425763836081]
[0.01638412 0.04453665 0.04453665 0.89454258]
tf.Tensor([0.01638412 0.04453665 0.04453665 0.8945426 ], shape=(4,), dtype=float32)
0.9999999999999999


# Sigmoid

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/a26a3fa3cbb41a3abfe4c7ff88d47f0181489d13)

In [13]:
import math
def sigmoid(z):
    return [1 / (1 + math.exp(-n)) for n in z]
def np_sigmoid(z):
    return [1/(1 + np.exp(-n)) for n in z]

In [14]:
import tensorflow as tf
n = [1.0, 2.0, 2.0, 5.0]
print(sigmoid(n))
print(np_sigmoid(n))
print(tf.nn.sigmoid(n))

[0.7310585786300049, 0.8807970779778823, 0.8807970779778823, 0.9933071490757153]
[0.7310585786300049, 0.8807970779778823, 0.8807970779778823, 0.9933071490757153]
tf.Tensor([0.7310586 0.880797  0.880797  0.9933072], shape=(4,), dtype=float32)


# relu

![](https://miro.medium.com/max/1400/1*ugxPV_0OL-LBN95LHZofUQ.jpeg)

In [29]:
def relu(z):
    return [i if i>0 else 0 for i in z  ]

def np_relu(z):
    return np.maximum(0,z)

def tn_relu(z):
    import tensorflow as tf
    return tf.maximum(z, 0)

In [31]:
import tensorflow as tf
n = [1.0, 2.0, 2.0, 5.0, -1.2]
print(relu(n))
print(np_relu(n))
print(tf.nn.relu(n))

[1.0, 2.0, 2.0, 5.0, 0]
[1. 2. 2. 5. 0.]
tf.Tensor([1. 2. 2. 5. 0.], shape=(5,), dtype=float32)


# Leaky Relu

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/7ef462b36056ff49700914fc305a39cd0d8c1ef1)

In [73]:
def leaky_relu(z):
    return [i if i>0 else 0.2*i for i in z  ]
def np_leakyRelu(z):
    out = np.array(z)
    out[out < 0] *= 0.2
    return out

In [74]:
import tensorflow as tf
n = [1.0, 2.0, 2.0, 5.0, -3.0, -5.0, -12.4]
print(leaky_relu(n))
print(np_leakyRelu(n))
print(tf.nn.leaky_relu(n))

[1.0, 2.0, 2.0, 5.0, -0.6000000000000001, -1.0, -2.4800000000000004]
[ 1.    2.    2.    5.   -0.6  -1.   -2.48]
tf.Tensor([ 1.    2.    2.    5.   -0.6  -1.   -2.48], shape=(7,), dtype=float32)


# Ref
https://www.depends-on-the-definition.com/guide-to-multi-label-classification-with-neural-networks/